version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    command: gunicorn main:app --bind 0.0.0.0:8000 --worker-class uvicorn.workers.UvicornWorker
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - ${DATABASE_PATH}:${DATABASE_PATH}
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
  certbot:
    build:
      dockerfile: Dockerfile
      context: ./certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --nginx; sleep 12h & wait $${!}; done;'"
