FROM certbot/certbot:latest
# This is the official certbot image, but it does not include nginx.
# The following line adds it.
# If this doesn't work, then the the docker file was 
RUN apk add --update certbot-nginx